// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_RandomVectorComponentImpl : CParticleFunctionInitializerImpl, C_INIT_RandomVectorComponent {

  public C_INIT_RandomVectorComponentImpl(nint handle) : base(handle) {
  }

  private static nint? _MinOffset;

  public ref float Min {
    get {
      if (_MinOffset == null) {
        _MinOffset = Schema.GetOffset(0xD6D670313B1A5649);
      }
      return ref _Handle.AsRef<float>(_MinOffset!.Value);
    }
  }
  private static nint? _MaxOffset;

  public ref float Max {
    get {
      if (_MaxOffset == null) {
        _MaxOffset = Schema.GetOffset(0xD6D670312D06B887);
      }
      return ref _Handle.AsRef<float>(_MaxOffset!.Value);
    }
  }
  private static nint? _FieldOutputOffset;

  public ParticleAttributeIndex_t FieldOutput {
    get {
      if (_FieldOutputOffset == null) {
        _FieldOutputOffset = Schema.GetOffset(0xD6D67031E5729606);
      }
      return new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset!.Value);
    }
  }
  private static nint? _ComponentOffset;

  public ref int Component {
    get {
      if (_ComponentOffset == null) {
        _ComponentOffset = Schema.GetOffset(0xD6D67031BFD0952C);
      }
      return ref _Handle.AsRef<int>(_ComponentOffset!.Value);
    }
  }


}