// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_AddVectorToVectorImpl : CParticleFunctionInitializerImpl, C_INIT_AddVectorToVector {

  public C_INIT_AddVectorToVectorImpl(nint handle) : base(handle) {
  }

  private static nint? _ScaleOffset;

  public ref Vector Scale {
    get {
      if (_ScaleOffset == null) {
        _ScaleOffset = Schema.GetOffset(0xFBD8AC005F596B51);
      }
      return ref _Handle.AsRef<Vector>(_ScaleOffset!.Value);
    }
  }
  private static nint? _FieldOutputOffset;

  public ParticleAttributeIndex_t FieldOutput {
    get {
      if (_FieldOutputOffset == null) {
        _FieldOutputOffset = Schema.GetOffset(0xFBD8AC00E5729606);
      }
      return new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset!.Value);
    }
  }
  private static nint? _FieldInputOffset;

  public ParticleAttributeIndex_t FieldInput {
    get {
      if (_FieldInputOffset == null) {
        _FieldInputOffset = Schema.GetOffset(0xFBD8AC00AE775669);
      }
      return new ParticleAttributeIndex_tImpl(_Handle + _FieldInputOffset!.Value);
    }
  }
  private static nint? _OffsetMinOffset;

  public ref Vector OffsetMin {
    get {
      if (_OffsetMinOffset == null) {
        _OffsetMinOffset = Schema.GetOffset(0xFBD8AC00ABED1082);
      }
      return ref _Handle.AsRef<Vector>(_OffsetMinOffset!.Value);
    }
  }
  private static nint? _OffsetMaxOffset;

  public ref Vector OffsetMax {
    get {
      if (_OffsetMaxOffset == null) {
        _OffsetMaxOffset = Schema.GetOffset(0xFBD8AC0095D96628);
      }
      return ref _Handle.AsRef<Vector>(_OffsetMaxOffset!.Value);
    }
  }
  private static nint? _RandomnessParametersOffset;

  public CRandomNumberGeneratorParameters RandomnessParameters {
    get {
      if (_RandomnessParametersOffset == null) {
        _RandomnessParametersOffset = Schema.GetOffset(0xFBD8AC007EDF50AD);
      }
      return new CRandomNumberGeneratorParametersImpl(_Handle + _RandomnessParametersOffset!.Value);
    }
  }


}