// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_CreateAlongPathImpl : CParticleFunctionInitializerImpl, C_INIT_CreateAlongPath {

  public C_INIT_CreateAlongPathImpl(nint handle) : base(handle) {
  }

  private static nint? _MaxDistanceOffset;

  public ref float MaxDistance {
    get {
      if (_MaxDistanceOffset == null) {
        _MaxDistanceOffset = Schema.GetOffset(0x655F7B0C844E396A);
      }
      return ref _Handle.AsRef<float>(_MaxDistanceOffset!.Value);
    }
  }
  private static nint? _PathParamsOffset;

  public CPathParameters PathParams {
    get {
      if (_PathParamsOffset == null) {
        _PathParamsOffset = Schema.GetOffset(0x655F7B0C3C10092C);
      }
      return new CPathParametersImpl(_Handle + _PathParamsOffset!.Value);
    }
  }
  private static nint? _UseRandomCPsOffset;

  public ref bool UseRandomCPs {
    get {
      if (_UseRandomCPsOffset == null) {
        _UseRandomCPsOffset = Schema.GetOffset(0x655F7B0CA15D9A41);
      }
      return ref _Handle.AsRef<bool>(_UseRandomCPsOffset!.Value);
    }
  }
  private static nint? _EndOffsetOffset;

  public ref Vector EndOffset {
    get {
      if (_EndOffsetOffset == null) {
        _EndOffsetOffset = Schema.GetOffset(0x655F7B0C5BBD1959);
      }
      return ref _Handle.AsRef<Vector>(_EndOffsetOffset!.Value);
    }
  }
  private static nint? _SaveOffsetOffset;

  public ref bool SaveOffset {
    get {
      if (_SaveOffsetOffset == null) {
        _SaveOffsetOffset = Schema.GetOffset(0x655F7B0C43F64E5B);
      }
      return ref _Handle.AsRef<bool>(_SaveOffsetOffset!.Value);
    }
  }


}