// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RemapDotProductToScalarImpl : CParticleFunctionOperatorImpl, C_OP_RemapDotProductToScalar {

  public C_OP_RemapDotProductToScalarImpl(nint handle) : base(handle) {
  }

  private static nint? _InputCP1Offset;

  public ref int InputCP1 {
    get {
      if (_InputCP1Offset == null) {
        _InputCP1Offset = Schema.GetOffset(0x56A85935A0CCAE3F);
      }
      return ref _Handle.AsRef<int>(_InputCP1Offset!.Value);
    }
  }
  private static nint? _InputCP2Offset;

  public ref int InputCP2 {
    get {
      if (_InputCP2Offset == null) {
        _InputCP2Offset = Schema.GetOffset(0x56A85935A1CCAFD2);
      }
      return ref _Handle.AsRef<int>(_InputCP2Offset!.Value);
    }
  }
  private static nint? _FieldOutputOffset;

  public ParticleAttributeIndex_t FieldOutput {
    get {
      if (_FieldOutputOffset == null) {
        _FieldOutputOffset = Schema.GetOffset(0x56A85935E5729606);
      }
      return new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset!.Value);
    }
  }
  private static nint? _InputMinOffset;

  public ref float InputMin {
    get {
      if (_InputMinOffset == null) {
        _InputMinOffset = Schema.GetOffset(0x56A85935E88A0D0F);
      }
      return ref _Handle.AsRef<float>(_InputMinOffset!.Value);
    }
  }
  private static nint? _InputMaxOffset;

  public ref float InputMax {
    get {
      if (_InputMaxOffset == null) {
        _InputMaxOffset = Schema.GetOffset(0x56A85935D6766901);
      }
      return ref _Handle.AsRef<float>(_InputMaxOffset!.Value);
    }
  }
  private static nint? _OutputMinOffset;

  public ref float OutputMin {
    get {
      if (_OutputMinOffset == null) {
        _OutputMinOffset = Schema.GetOffset(0x56A859355F8D7716);
      }
      return ref _Handle.AsRef<float>(_OutputMinOffset!.Value);
    }
  }
  private static nint? _OutputMaxOffset;

  public ref float OutputMax {
    get {
      if (_OutputMaxOffset == null) {
        _OutputMaxOffset = Schema.GetOffset(0x56A8593551A0E8C4);
      }
      return ref _Handle.AsRef<float>(_OutputMaxOffset!.Value);
    }
  }
  private static nint? _UseParticleVelocityOffset;

  public ref bool UseParticleVelocity {
    get {
      if (_UseParticleVelocityOffset == null) {
        _UseParticleVelocityOffset = Schema.GetOffset(0x56A85935412A8335);
      }
      return ref _Handle.AsRef<bool>(_UseParticleVelocityOffset!.Value);
    }
  }
  private static nint? _SetMethodOffset;

  public ref ParticleSetMethod_t SetMethod {
    get {
      if (_SetMethodOffset == null) {
        _SetMethodOffset = Schema.GetOffset(0x56A85935FB53C31E);
      }
      return ref _Handle.AsRef<ParticleSetMethod_t>(_SetMethodOffset!.Value);
    }
  }
  private static nint? _ActiveRangeOffset;

  public ref bool ActiveRange {
    get {
      if (_ActiveRangeOffset == null) {
        _ActiveRangeOffset = Schema.GetOffset(0x56A859353FA53B84);
      }
      return ref _Handle.AsRef<bool>(_ActiveRangeOffset!.Value);
    }
  }
  private static nint? _UseParticleNormalOffset;

  public ref bool UseParticleNormal {
    get {
      if (_UseParticleNormalOffset == null) {
        _UseParticleNormalOffset = Schema.GetOffset(0x56A859353FBCD9B5);
      }
      return ref _Handle.AsRef<bool>(_UseParticleNormalOffset!.Value);
    }
  }


}