// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_DifferencePreviousParticleImpl : CParticleFunctionOperatorImpl, C_OP_DifferencePreviousParticle {

  public C_OP_DifferencePreviousParticleImpl(nint handle) : base(handle) {
  }

  private static nint? _FieldInputOffset;

  public ParticleAttributeIndex_t FieldInput {
    get {
      if (_FieldInputOffset == null) {
        _FieldInputOffset = Schema.GetOffset(0xD626A7A9AE775669);
      }
      return new ParticleAttributeIndex_tImpl(_Handle + _FieldInputOffset!.Value);
    }
  }
  private static nint? _FieldOutputOffset;

  public ParticleAttributeIndex_t FieldOutput {
    get {
      if (_FieldOutputOffset == null) {
        _FieldOutputOffset = Schema.GetOffset(0xD626A7A9E5729606);
      }
      return new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset!.Value);
    }
  }
  private static nint? _InputMinOffset;

  public ref float InputMin {
    get {
      if (_InputMinOffset == null) {
        _InputMinOffset = Schema.GetOffset(0xD626A7A9E88A0D0F);
      }
      return ref _Handle.AsRef<float>(_InputMinOffset!.Value);
    }
  }
  private static nint? _InputMaxOffset;

  public ref float InputMax {
    get {
      if (_InputMaxOffset == null) {
        _InputMaxOffset = Schema.GetOffset(0xD626A7A9D6766901);
      }
      return ref _Handle.AsRef<float>(_InputMaxOffset!.Value);
    }
  }
  private static nint? _OutputMinOffset;

  public ref float OutputMin {
    get {
      if (_OutputMinOffset == null) {
        _OutputMinOffset = Schema.GetOffset(0xD626A7A95F8D7716);
      }
      return ref _Handle.AsRef<float>(_OutputMinOffset!.Value);
    }
  }
  private static nint? _OutputMaxOffset;

  public ref float OutputMax {
    get {
      if (_OutputMaxOffset == null) {
        _OutputMaxOffset = Schema.GetOffset(0xD626A7A951A0E8C4);
      }
      return ref _Handle.AsRef<float>(_OutputMaxOffset!.Value);
    }
  }
  private static nint? _SetMethodOffset;

  public ref ParticleSetMethod_t SetMethod {
    get {
      if (_SetMethodOffset == null) {
        _SetMethodOffset = Schema.GetOffset(0xD626A7A9FB53C31E);
      }
      return ref _Handle.AsRef<ParticleSetMethod_t>(_SetMethodOffset!.Value);
    }
  }
  private static nint? _ActiveRangeOffset;

  public ref bool ActiveRange {
    get {
      if (_ActiveRangeOffset == null) {
        _ActiveRangeOffset = Schema.GetOffset(0xD626A7A93FA53B84);
      }
      return ref _Handle.AsRef<bool>(_ActiveRangeOffset!.Value);
    }
  }
  private static nint? _SetPreviousParticleOffset;

  public ref bool SetPreviousParticle {
    get {
      if (_SetPreviousParticleOffset == null) {
        _SetPreviousParticleOffset = Schema.GetOffset(0xD626A7A9BDC03798);
      }
      return ref _Handle.AsRef<bool>(_SetPreviousParticleOffset!.Value);
    }
  }


}