// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_ScreenSpacePositionOfTargetImpl : CParticleFunctionOperatorImpl, C_OP_ScreenSpacePositionOfTarget {

  public C_OP_ScreenSpacePositionOfTargetImpl(nint handle) : base(handle) {
  }

  private static nint? _TargetPositionOffset;

  public CPerParticleVecInput TargetPosition {
    get {
      if (_TargetPositionOffset == null) {
        _TargetPositionOffset = Schema.GetOffset(0x5FF537BA554C563B);
      }
      return new CPerParticleVecInputImpl(_Handle + _TargetPositionOffset!.Value);
    }
  }
  private static nint? _OututBehindnessOffset;

  public ref bool OututBehindness {
    get {
      if (_OututBehindnessOffset == null) {
        _OututBehindnessOffset = Schema.GetOffset(0x5FF537BADB123D49);
      }
      return ref _Handle.AsRef<bool>(_OututBehindnessOffset!.Value);
    }
  }
  private static nint? _BehindFieldOutputOffset;

  public ParticleAttributeIndex_t BehindFieldOutput {
    get {
      if (_BehindFieldOutputOffset == null) {
        _BehindFieldOutputOffset = Schema.GetOffset(0x5FF537BA69F4F392);
      }
      return new ParticleAttributeIndex_tImpl(_Handle + _BehindFieldOutputOffset!.Value);
    }
  }
  private static nint? _BehindOutputRemapOffset;

  public CParticleRemapFloatInput BehindOutputRemap {
    get {
      if (_BehindOutputRemapOffset == null) {
        _BehindOutputRemapOffset = Schema.GetOffset(0x5FF537BA4B35FBF3);
      }
      return new CParticleRemapFloatInputImpl(_Handle + _BehindOutputRemapOffset!.Value);
    }
  }
  private static nint? _BehindSetMethodOffset;

  public ref ParticleSetMethod_t BehindSetMethod {
    get {
      if (_BehindSetMethodOffset == null) {
        _BehindSetMethodOffset = Schema.GetOffset(0x5FF537BAFE7A7BDA);
      }
      return ref _Handle.AsRef<ParticleSetMethod_t>(_BehindSetMethodOffset!.Value);
    }
  }


}