// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_SetVecImpl : CParticleFunctionOperatorImpl, C_OP_SetVec {

  public C_OP_SetVecImpl(nint handle) : base(handle) {
  }

  private static nint? _InputValueOffset;

  public CPerParticleVecInput InputValue {
    get {
      if (_InputValueOffset == null) {
        _InputValueOffset = Schema.GetOffset(0x24E155B734445438);
      }
      return new CPerParticleVecInputImpl(_Handle + _InputValueOffset!.Value);
    }
  }
  private static nint? _OutputFieldOffset;

  public ParticleAttributeIndex_t OutputField {
    get {
      if (_OutputFieldOffset == null) {
        _OutputFieldOffset = Schema.GetOffset(0x24E155B7324F6F74);
      }
      return new ParticleAttributeIndex_tImpl(_Handle + _OutputFieldOffset!.Value);
    }
  }
  private static nint? _SetMethodOffset;

  public ref ParticleSetMethod_t SetMethod {
    get {
      if (_SetMethodOffset == null) {
        _SetMethodOffset = Schema.GetOffset(0x24E155B7FB53C31E);
      }
      return ref _Handle.AsRef<ParticleSetMethod_t>(_SetMethodOffset!.Value);
    }
  }
  private static nint? _LerpOffset;

  public CPerParticleFloatInput Lerp {
    get {
      if (_LerpOffset == null) {
        _LerpOffset = Schema.GetOffset(0x24E155B75C17F8E8);
      }
      return new CPerParticleFloatInputImpl(_Handle + _LerpOffset!.Value);
    }
  }
  private static nint? _NormalizedOutputOffset;

  public ref bool NormalizedOutput {
    get {
      if (_NormalizedOutputOffset == null) {
        _NormalizedOutputOffset = Schema.GetOffset(0x24E155B70AA98C55);
      }
      return ref _Handle.AsRef<bool>(_NormalizedOutputOffset!.Value);
    }
  }


}