// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimFootImpl : SchemaClass, CAnimFoot {

  public CAnimFootImpl(nint handle) : base(handle) {
  }

  private static nint? _NameOffset;

  public string Name {
    get {
      if (_NameOffset == null) {
        _NameOffset = Schema.GetOffset(0x583A05E34D8F5786);
      }
      var ptr = _Handle.Read<nint>(_NameOffset!.Value);
      return Schema.GetString(ptr);
    }
    set {
      if (_NameOffset == null) {
        _NameOffset = Schema.GetOffset(0x583A05E34D8F5786);
      }
      Schema.SetString(_Handle, _NameOffset!.Value, value);
    }
  } 
  private static nint? _BallOffsetOffset;

  public ref Vector BallOffset {
    get {
      if (_BallOffsetOffset == null) {
        _BallOffsetOffset = Schema.GetOffset(0x583A05E3E3376F1B);
      }
      return ref _Handle.AsRef<Vector>(_BallOffsetOffset!.Value);
    }
  }
  private static nint? _HeelOffsetOffset;

  public ref Vector HeelOffset {
    get {
      if (_HeelOffsetOffset == null) {
        _HeelOffsetOffset = Schema.GetOffset(0x583A05E3306AE608);
      }
      return ref _Handle.AsRef<Vector>(_HeelOffsetOffset!.Value);
    }
  }
  private static nint? _AnkleBoneIndexOffset;

  public ref int AnkleBoneIndex {
    get {
      if (_AnkleBoneIndexOffset == null) {
        _AnkleBoneIndexOffset = Schema.GetOffset(0x583A05E31E89F146);
      }
      return ref _Handle.AsRef<int>(_AnkleBoneIndexOffset!.Value);
    }
  }
  private static nint? _ToeBoneIndexOffset;

  public ref int ToeBoneIndex {
    get {
      if (_ToeBoneIndexOffset == null) {
        _ToeBoneIndexOffset = Schema.GetOffset(0x583A05E3EEF7CC57);
      }
      return ref _Handle.AsRef<int>(_ToeBoneIndexOffset!.Value);
    }
  }


}