// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBasePlayerWeaponVDataImpl : CEntitySubclassVDataBaseImpl, CBasePlayerWeaponVData {

  public CBasePlayerWeaponVDataImpl(nint handle) : base(handle) {
  }

  private static nint? _WorldModelOffset;

  public SchemaUntypedField WorldModel {
    get {
      if (_WorldModelOffset == null) {
        _WorldModelOffset = Schema.GetOffset(0x64E418A0B9041909);
      }
      return new SchemaUntypedField(_Handle + _WorldModelOffset!.Value);
    }
  }
  private static nint? _ToolsOnlyOwnerModelNameOffset;

  public SchemaUntypedField ToolsOnlyOwnerModelName {
    get {
      if (_ToolsOnlyOwnerModelNameOffset == null) {
        _ToolsOnlyOwnerModelNameOffset = Schema.GetOffset(0x64E418A06DD9DD04);
      }
      return new SchemaUntypedField(_Handle + _ToolsOnlyOwnerModelNameOffset!.Value);
    }
  }
  private static nint? _BuiltRightHandedOffset;

  public ref bool BuiltRightHanded {
    get {
      if (_BuiltRightHandedOffset == null) {
        _BuiltRightHandedOffset = Schema.GetOffset(0x64E418A08857B74F);
      }
      return ref _Handle.AsRef<bool>(_BuiltRightHandedOffset!.Value);
    }
  }
  private static nint? _AllowFlippingOffset;

  public ref bool AllowFlipping {
    get {
      if (_AllowFlippingOffset == null) {
        _AllowFlippingOffset = Schema.GetOffset(0x64E418A01B594D05);
      }
      return ref _Handle.AsRef<bool>(_AllowFlippingOffset!.Value);
    }
  }
  private static nint? _MuzzleAttachmentOffset;

  public SchemaUntypedField MuzzleAttachment {
    get {
      if (_MuzzleAttachmentOffset == null) {
        _MuzzleAttachmentOffset = Schema.GetOffset(0x64E418A0E8A8FEA2);
      }
      return new SchemaUntypedField(_Handle + _MuzzleAttachmentOffset!.Value);
    }
  }
  private static nint? _MuzzleFlashParticleOffset;

  public SchemaUntypedField MuzzleFlashParticle {
    get {
      if (_MuzzleFlashParticleOffset == null) {
        _MuzzleFlashParticleOffset = Schema.GetOffset(0x64E418A0CE0726A3);
      }
      return new SchemaUntypedField(_Handle + _MuzzleFlashParticleOffset!.Value);
    }
  }
  private static nint? _MuzzleFlashParticleConfigOffset;

  public string MuzzleFlashParticleConfig {
    get {
      if (_MuzzleFlashParticleConfigOffset == null) {
        _MuzzleFlashParticleConfigOffset = Schema.GetOffset(0x64E418A029D7C081);
      }
      var ptr = _Handle.Read<nint>(_MuzzleFlashParticleConfigOffset!.Value);
      return Schema.GetString(ptr);
    }
    set {
      if (_MuzzleFlashParticleConfigOffset == null) {
        _MuzzleFlashParticleConfigOffset = Schema.GetOffset(0x64E418A029D7C081);
      }
      Schema.SetString(_Handle, _MuzzleFlashParticleConfigOffset!.Value, value);
    }
  } 
  private static nint? _BarrelSmokeParticleOffset;

  public SchemaUntypedField BarrelSmokeParticle {
    get {
      if (_BarrelSmokeParticleOffset == null) {
        _BarrelSmokeParticleOffset = Schema.GetOffset(0x64E418A03406364F);
      }
      return new SchemaUntypedField(_Handle + _BarrelSmokeParticleOffset!.Value);
    }
  }
  private static nint? _MuzzleSmokeShotThresholdOffset;

  public ref byte MuzzleSmokeShotThreshold {
    get {
      if (_MuzzleSmokeShotThresholdOffset == null) {
        _MuzzleSmokeShotThresholdOffset = Schema.GetOffset(0x64E418A036780024);
      }
      return ref _Handle.AsRef<byte>(_MuzzleSmokeShotThresholdOffset!.Value);
    }
  }
  private static nint? _MuzzleSmokeTimeoutOffset;

  public ref float MuzzleSmokeTimeout {
    get {
      if (_MuzzleSmokeTimeoutOffset == null) {
        _MuzzleSmokeTimeoutOffset = Schema.GetOffset(0x64E418A06F626E1A);
      }
      return ref _Handle.AsRef<float>(_MuzzleSmokeTimeoutOffset!.Value);
    }
  }
  private static nint? _MuzzleSmokeDecrementRateOffset;

  public ref float MuzzleSmokeDecrementRate {
    get {
      if (_MuzzleSmokeDecrementRateOffset == null) {
        _MuzzleSmokeDecrementRateOffset = Schema.GetOffset(0x64E418A0B407F926);
      }
      return ref _Handle.AsRef<float>(_MuzzleSmokeDecrementRateOffset!.Value);
    }
  }
  private static nint? _LinkedCooldownsOffset;

  public ref bool LinkedCooldowns {
    get {
      if (_LinkedCooldownsOffset == null) {
        _LinkedCooldownsOffset = Schema.GetOffset(0x64E418A039951A46);
      }
      return ref _Handle.AsRef<bool>(_LinkedCooldownsOffset!.Value);
    }
  }
  private static nint? _FlagsOffset;

  public ref ItemFlagTypes_t Flags {
    get {
      if (_FlagsOffset == null) {
        _FlagsOffset = Schema.GetOffset(0x64E418A01873A1F7);
      }
      return ref _Handle.AsRef<ItemFlagTypes_t>(_FlagsOffset!.Value);
    }
  }
  private static nint? _PrimaryAmmoTypeOffset;

  public AmmoIndex_t PrimaryAmmoType {
    get {
      if (_PrimaryAmmoTypeOffset == null) {
        _PrimaryAmmoTypeOffset = Schema.GetOffset(0x64E418A05686E507);
      }
      return new AmmoIndex_tImpl(_Handle + _PrimaryAmmoTypeOffset!.Value);
    }
  }
  private static nint? _SecondaryAmmoTypeOffset;

  public AmmoIndex_t SecondaryAmmoType {
    get {
      if (_SecondaryAmmoTypeOffset == null) {
        _SecondaryAmmoTypeOffset = Schema.GetOffset(0x64E418A046D1E9A7);
      }
      return new AmmoIndex_tImpl(_Handle + _SecondaryAmmoTypeOffset!.Value);
    }
  }
  private static nint? _MaxClip1Offset;

  public ref int MaxClip1 {
    get {
      if (_MaxClip1Offset == null) {
        _MaxClip1Offset = Schema.GetOffset(0x64E418A0EF951A4F);
      }
      return ref _Handle.AsRef<int>(_MaxClip1Offset!.Value);
    }
  }
  private static nint? _MaxClip2Offset;

  public ref int MaxClip2 {
    get {
      if (_MaxClip2Offset == null) {
        _MaxClip2Offset = Schema.GetOffset(0x64E418A0F0951BE2);
      }
      return ref _Handle.AsRef<int>(_MaxClip2Offset!.Value);
    }
  }
  private static nint? _DefaultClip1Offset;

  public ref int DefaultClip1 {
    get {
      if (_DefaultClip1Offset == null) {
        _DefaultClip1Offset = Schema.GetOffset(0x64E418A0999A5252);
      }
      return ref _Handle.AsRef<int>(_DefaultClip1Offset!.Value);
    }
  }
  private static nint? _DefaultClip2Offset;

  public ref int DefaultClip2 {
    get {
      if (_DefaultClip2Offset == null) {
        _DefaultClip2Offset = Schema.GetOffset(0x64E418A0989A50BF);
      }
      return ref _Handle.AsRef<int>(_DefaultClip2Offset!.Value);
    }
  }
  private static nint? _ReserveAmmoAsClipsOffset;

  public ref bool ReserveAmmoAsClips {
    get {
      if (_ReserveAmmoAsClipsOffset == null) {
        _ReserveAmmoAsClipsOffset = Schema.GetOffset(0x64E418A016F78884);
      }
      return ref _Handle.AsRef<bool>(_ReserveAmmoAsClipsOffset!.Value);
    }
  }
  private static nint? _TreatAsSingleClipOffset;

  public ref bool TreatAsSingleClip {
    get {
      if (_TreatAsSingleClipOffset == null) {
        _TreatAsSingleClipOffset = Schema.GetOffset(0x64E418A01B25858D);
      }
      return ref _Handle.AsRef<bool>(_TreatAsSingleClipOffset!.Value);
    }
  }
  private static nint? _KeepLoadedAmmoOffset;

  public ref bool KeepLoadedAmmo {
    get {
      if (_KeepLoadedAmmoOffset == null) {
        _KeepLoadedAmmoOffset = Schema.GetOffset(0x64E418A0C9C228BF);
      }
      return ref _Handle.AsRef<bool>(_KeepLoadedAmmoOffset!.Value);
    }
  }
  private static nint? _WeightOffset;

  public ref int Weight {
    get {
      if (_WeightOffset == null) {
        _WeightOffset = Schema.GetOffset(0x64E418A054A5EA14);
      }
      return ref _Handle.AsRef<int>(_WeightOffset!.Value);
    }
  }
  private static nint? _AutoSwitchToOffset;

  public ref bool AutoSwitchTo {
    get {
      if (_AutoSwitchToOffset == null) {
        _AutoSwitchToOffset = Schema.GetOffset(0x64E418A01E225763);
      }
      return ref _Handle.AsRef<bool>(_AutoSwitchToOffset!.Value);
    }
  }
  private static nint? _AutoSwitchFromOffset;

  public ref bool AutoSwitchFrom {
    get {
      if (_AutoSwitchFromOffset == null) {
        _AutoSwitchFromOffset = Schema.GetOffset(0x64E418A01E5E509A);
      }
      return ref _Handle.AsRef<bool>(_AutoSwitchFromOffset!.Value);
    }
  }
  private static nint? _RumbleEffectOffset;

  public ref RumbleEffect_t RumbleEffect {
    get {
      if (_RumbleEffectOffset == null) {
        _RumbleEffectOffset = Schema.GetOffset(0x64E418A0C5F24460);
      }
      return ref _Handle.AsRef<RumbleEffect_t>(_RumbleEffectOffset!.Value);
    }
  }
  private static nint? _DropSpeedOffset;

  public ref float DropSpeed {
    get {
      if (_DropSpeedOffset == null) {
        _DropSpeedOffset = Schema.GetOffset(0x64E418A005B18969);
      }
      return ref _Handle.AsRef<float>(_DropSpeedOffset!.Value);
    }
  }
  private static nint? _SlotOffset;

  public ref int Slot {
    get {
      if (_SlotOffset == null) {
        _SlotOffset = Schema.GetOffset(0x64E418A0AC7A8798);
      }
      return ref _Handle.AsRef<int>(_SlotOffset!.Value);
    }
  }
  private static nint? _PositionOffset;

  public ref int Position {
    get {
      if (_PositionOffset == null) {
        _PositionOffset = Schema.GetOffset(0x64E418A00617DD77);
      }
      return ref _Handle.AsRef<int>(_PositionOffset!.Value);
    }
  }
  private static nint? _ShootSoundsOffset;

  public SchemaUntypedField ShootSounds {
    get {
      if (_ShootSoundsOffset == null) {
        _ShootSoundsOffset = Schema.GetOffset(0x64E418A0DF14A83B);
      }
      return new SchemaUntypedField(_Handle + _ShootSoundsOffset!.Value);
    }
  }


}