// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBaseDoorImpl : CBaseToggleImpl, CBaseDoor {

  public CBaseDoorImpl(nint handle) : base(handle) {
  }

  private static nint? _MoveEntitySpaceOffset;

  public ref QAngle MoveEntitySpace {
    get {
      if (_MoveEntitySpaceOffset == null) {
        _MoveEntitySpaceOffset = Schema.GetOffset(0x798B70E7325319F9);
      }
      return ref _Handle.AsRef<QAngle>(_MoveEntitySpaceOffset!.Value);
    }
  }
  private static nint? _MoveDirParentSpaceOffset;

  public ref Vector MoveDirParentSpace {
    get {
      if (_MoveDirParentSpaceOffset == null) {
        _MoveDirParentSpaceOffset = Schema.GetOffset(0x798B70E7EC2120EF);
      }
      return ref _Handle.AsRef<Vector>(_MoveDirParentSpaceOffset!.Value);
    }
  }
  private static nint? _LsOffset;

  public locksound_t Ls {
    get {
      if (_LsOffset == null) {
        _LsOffset = Schema.GetOffset(0x798B70E7D3B05E88);
      }
      return new locksound_tImpl(_Handle + _LsOffset!.Value);
    }
  }
  private static nint? _ForceClosedOffset;

  public ref bool ForceClosed {
    get {
      if (_ForceClosedOffset == null) {
        _ForceClosedOffset = Schema.GetOffset(0x798B70E7397D7E34);
      }
      return ref _Handle.AsRef<bool>(_ForceClosedOffset!.Value);
    }
  }
  private static nint? _DoorGroupOffset;

  public ref bool DoorGroup {
    get {
      if (_DoorGroupOffset == null) {
        _DoorGroupOffset = Schema.GetOffset(0x798B70E7391E1820);
      }
      return ref _Handle.AsRef<bool>(_DoorGroupOffset!.Value);
    }
  }
  private static nint? _LockedOffset;

  public ref bool Locked {
    get {
      if (_LockedOffset == null) {
        _LockedOffset = Schema.GetOffset(0x798B70E7D08E97F3);
      }
      return ref _Handle.AsRef<bool>(_LockedOffset!.Value);
    }
  }
  private static nint? _IgnoreDebrisOffset;

  public ref bool IgnoreDebris {
    get {
      if (_IgnoreDebrisOffset == null) {
        _IgnoreDebrisOffset = Schema.GetOffset(0x798B70E7A67DDAD4);
      }
      return ref _Handle.AsRef<bool>(_IgnoreDebrisOffset!.Value);
    }
  }
  private static nint? _NoNPCsOffset;

  public ref bool NoNPCs {
    get {
      if (_NoNPCsOffset == null) {
        _NoNPCsOffset = Schema.GetOffset(0x798B70E7237405C2);
      }
      return ref _Handle.AsRef<bool>(_NoNPCsOffset!.Value);
    }
  }
  private static nint? _SpawnPositionOffset;

  public ref FuncDoorSpawnPos_t SpawnPosition {
    get {
      if (_SpawnPositionOffset == null) {
        _SpawnPositionOffset = Schema.GetOffset(0x798B70E7F5AD878C);
      }
      return ref _Handle.AsRef<FuncDoorSpawnPos_t>(_SpawnPositionOffset!.Value);
    }
  }
  private static nint? _BlockDamageOffset;

  public ref float BlockDamage {
    get {
      if (_BlockDamageOffset == null) {
        _BlockDamageOffset = Schema.GetOffset(0x798B70E7A5348091);
      }
      return ref _Handle.AsRef<float>(_BlockDamageOffset!.Value);
    }
  }
  private static nint? _NoiseMovingOffset;

  public string NoiseMoving {
    get {
      if (_NoiseMovingOffset == null) {
        _NoiseMovingOffset = Schema.GetOffset(0x798B70E7415AB84B);
      }
      var ptr = _Handle.Read<nint>(_NoiseMovingOffset!.Value);
      return Schema.GetString(ptr);
    }
    set {
      if (_NoiseMovingOffset == null) {
        _NoiseMovingOffset = Schema.GetOffset(0x798B70E7415AB84B);
      }
      Schema.SetString(_Handle, _NoiseMovingOffset!.Value, value);
    }
  } 
  private static nint? _NoiseArrivedOffset;

  public string NoiseArrived {
    get {
      if (_NoiseArrivedOffset == null) {
        _NoiseArrivedOffset = Schema.GetOffset(0x798B70E7D2CDE47A);
      }
      var ptr = _Handle.Read<nint>(_NoiseArrivedOffset!.Value);
      return Schema.GetString(ptr);
    }
    set {
      if (_NoiseArrivedOffset == null) {
        _NoiseArrivedOffset = Schema.GetOffset(0x798B70E7D2CDE47A);
      }
      Schema.SetString(_Handle, _NoiseArrivedOffset!.Value, value);
    }
  } 
  private static nint? _NoiseMovingClosedOffset;

  public string NoiseMovingClosed {
    get {
      if (_NoiseMovingClosedOffset == null) {
        _NoiseMovingClosedOffset = Schema.GetOffset(0x798B70E7ED56FC0F);
      }
      var ptr = _Handle.Read<nint>(_NoiseMovingClosedOffset!.Value);
      return Schema.GetString(ptr);
    }
    set {
      if (_NoiseMovingClosedOffset == null) {
        _NoiseMovingClosedOffset = Schema.GetOffset(0x798B70E7ED56FC0F);
      }
      Schema.SetString(_Handle, _NoiseMovingClosedOffset!.Value, value);
    }
  } 
  private static nint? _NoiseArrivedClosedOffset;

  public string NoiseArrivedClosed {
    get {
      if (_NoiseArrivedClosedOffset == null) {
        _NoiseArrivedClosedOffset = Schema.GetOffset(0x798B70E78637F9A6);
      }
      var ptr = _Handle.Read<nint>(_NoiseArrivedClosedOffset!.Value);
      return Schema.GetString(ptr);
    }
    set {
      if (_NoiseArrivedClosedOffset == null) {
        _NoiseArrivedClosedOffset = Schema.GetOffset(0x798B70E78637F9A6);
      }
      Schema.SetString(_Handle, _NoiseArrivedClosedOffset!.Value, value);
    }
  } 
  private static nint? _ChainTargetOffset;

  public string ChainTarget {
    get {
      if (_ChainTargetOffset == null) {
        _ChainTargetOffset = Schema.GetOffset(0x798B70E762B5A227);
      }
      var ptr = _Handle.Read<nint>(_ChainTargetOffset!.Value);
      return Schema.GetString(ptr);
    }
    set {
      if (_ChainTargetOffset == null) {
        _ChainTargetOffset = Schema.GetOffset(0x798B70E762B5A227);
      }
      Schema.SetString(_Handle, _ChainTargetOffset!.Value, value);
    }
  } 
  private static nint? _OnBlockedClosingOffset;

  public CEntityIOOutput OnBlockedClosing {
    get {
      if (_OnBlockedClosingOffset == null) {
        _OnBlockedClosingOffset = Schema.GetOffset(0x798B70E7EC8BC45F);
      }
      return new CEntityIOOutputImpl(_Handle + _OnBlockedClosingOffset!.Value);
    }
  }
  private static nint? _OnBlockedOpeningOffset;

  public CEntityIOOutput OnBlockedOpening {
    get {
      if (_OnBlockedOpeningOffset == null) {
        _OnBlockedOpeningOffset = Schema.GetOffset(0x798B70E7F0BA7AA8);
      }
      return new CEntityIOOutputImpl(_Handle + _OnBlockedOpeningOffset!.Value);
    }
  }
  private static nint? _OnUnblockedClosingOffset;

  public CEntityIOOutput OnUnblockedClosing {
    get {
      if (_OnUnblockedClosingOffset == null) {
        _OnUnblockedClosingOffset = Schema.GetOffset(0x798B70E7B150C15C);
      }
      return new CEntityIOOutputImpl(_Handle + _OnUnblockedClosingOffset!.Value);
    }
  }
  private static nint? _OnUnblockedOpeningOffset;

  public CEntityIOOutput OnUnblockedOpening {
    get {
      if (_OnUnblockedOpeningOffset == null) {
        _OnUnblockedOpeningOffset = Schema.GetOffset(0x798B70E71AC8E62F);
      }
      return new CEntityIOOutputImpl(_Handle + _OnUnblockedOpeningOffset!.Value);
    }
  }
  private static nint? _OnFullyClosedOffset;

  public CEntityIOOutput OnFullyClosed {
    get {
      if (_OnFullyClosedOffset == null) {
        _OnFullyClosedOffset = Schema.GetOffset(0x798B70E775470294);
      }
      return new CEntityIOOutputImpl(_Handle + _OnFullyClosedOffset!.Value);
    }
  }
  private static nint? _OnFullyOpenOffset;

  public CEntityIOOutput OnFullyOpen {
    get {
      if (_OnFullyOpenOffset == null) {
        _OnFullyOpenOffset = Schema.GetOffset(0x798B70E721733AE4);
      }
      return new CEntityIOOutputImpl(_Handle + _OnFullyOpenOffset!.Value);
    }
  }
  private static nint? _OnCloseOffset;

  public CEntityIOOutput OnClose {
    get {
      if (_OnCloseOffset == null) {
        _OnCloseOffset = Schema.GetOffset(0x798B70E7BE036874);
      }
      return new CEntityIOOutputImpl(_Handle + _OnCloseOffset!.Value);
    }
  }
  private static nint? _OnOpenOffset;

  public CEntityIOOutput OnOpen {
    get {
      if (_OnOpenOffset == null) {
        _OnOpenOffset = Schema.GetOffset(0x798B70E7109A2278);
      }
      return new CEntityIOOutputImpl(_Handle + _OnOpenOffset!.Value);
    }
  }
  private static nint? _OnLockedUseOffset;

  public CEntityIOOutput OnLockedUse {
    get {
      if (_OnLockedUseOffset == null) {
        _OnLockedUseOffset = Schema.GetOffset(0x798B70E7FD62B6A1);
      }
      return new CEntityIOOutputImpl(_Handle + _OnLockedUseOffset!.Value);
    }
  }
  private static nint? _LoopMoveSoundOffset;

  public ref bool LoopMoveSound {
    get {
      if (_LoopMoveSoundOffset == null) {
        _LoopMoveSoundOffset = Schema.GetOffset(0x798B70E7A274AA19);
      }
      return ref _Handle.AsRef<bool>(_LoopMoveSoundOffset!.Value);
    }
  }
  private static nint? _CreateNavObstacleOffset;

  public ref bool CreateNavObstacle {
    get {
      if (_CreateNavObstacleOffset == null) {
        _CreateNavObstacleOffset = Schema.GetOffset(0x798B70E71849970B);
      }
      return ref _Handle.AsRef<bool>(_CreateNavObstacleOffset!.Value);
    }
  }
  private static nint? _IsChainingOffset;

  public ref bool IsChaining {
    get {
      if (_IsChainingOffset == null) {
        _IsChainingOffset = Schema.GetOffset(0x798B70E7A186D5CA);
      }
      return ref _Handle.AsRef<bool>(_IsChainingOffset!.Value);
    }
  }
  private static nint? _IsUsableOffset;

  public ref bool IsUsable {
    get {
      if (_IsUsableOffset == null) {
        _IsUsableOffset = Schema.GetOffset(0x798B70E799E20219);
      }
      return ref _Handle.AsRef<bool>(_IsUsableOffset!.Value);
    }
  }

  public void IsUsableUpdated() {
    Schema.Update(_Handle, 0x798B70E799E20219);
  }
}