// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBaseConstraintImpl : CBoneConstraintBaseImpl, CBaseConstraint {

  public CBaseConstraintImpl(nint handle) : base(handle) {
  }

  private static nint? _NameOffset;

  public string Name {
    get {
      if (_NameOffset == null) {
        _NameOffset = Schema.GetOffset(0xE972C2844D8F5786);
      }
      var ptr = _Handle.Read<nint>(_NameOffset!.Value);
      return Schema.GetString(ptr);
    }
    set {
      if (_NameOffset == null) {
        _NameOffset = Schema.GetOffset(0xE972C2844D8F5786);
      }
      Schema.SetString(_Handle, _NameOffset!.Value, value);
    }
  } 
  private static nint? _UpVectorOffset;

  public ref Vector UpVector {
    get {
      if (_UpVectorOffset == null) {
        _UpVectorOffset = Schema.GetOffset(0xE972C28487645F1B);
      }
      return ref _Handle.AsRef<Vector>(_UpVectorOffset!.Value);
    }
  }
  private static nint? _SlavesOffset;

  public ref CUtlLeanVector<CConstraintSlave, int> Slaves {
    get {
      if (_SlavesOffset == null) {
        _SlavesOffset = Schema.GetOffset(0xE972C284A62BA9E9);
      }
      return ref _Handle.AsRef<CUtlLeanVector<CConstraintSlave, int>>(_SlavesOffset!.Value);
    }
  }
  private static nint? _TargetsOffset;

  public ref CUtlVector<CConstraintTarget> Targets {
    get {
      if (_TargetsOffset == null) {
        _TargetsOffset = Schema.GetOffset(0xE972C28436A2FF01);
      }
      return ref _Handle.AsRef<CUtlVector<CConstraintTarget>>(_TargetsOffset!.Value);
    }
  }


}