// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBtActionAimImpl : CBtNodeImpl, CBtActionAim {

  public CBtActionAimImpl(nint handle) : base(handle) {
  }

  private static nint? _SensorInputKeyOffset;

  public string SensorInputKey {
    get {
      if (_SensorInputKeyOffset == null) {
        _SensorInputKeyOffset = Schema.GetOffset(0x43587513D2B0D4C1);
      }
      var ptr = _Handle.Read<nint>(_SensorInputKeyOffset!.Value);
      return Schema.GetString(ptr);
    }
    set {
      if (_SensorInputKeyOffset == null) {
        _SensorInputKeyOffset = Schema.GetOffset(0x43587513D2B0D4C1);
      }
      Schema.SetString(_Handle, _SensorInputKeyOffset!.Value, value);
    }
  } 
  private static nint? _AimReadyKeyOffset;

  public string AimReadyKey {
    get {
      if (_AimReadyKeyOffset == null) {
        _AimReadyKeyOffset = Schema.GetOffset(0x435875136718A4C7);
      }
      var ptr = _Handle.Read<nint>(_AimReadyKeyOffset!.Value);
      return Schema.GetString(ptr);
    }
    set {
      if (_AimReadyKeyOffset == null) {
        _AimReadyKeyOffset = Schema.GetOffset(0x435875136718A4C7);
      }
      Schema.SetString(_Handle, _AimReadyKeyOffset!.Value, value);
    }
  } 
  private static nint? _ZoomCooldownTimestampOffset;

  public ref float ZoomCooldownTimestamp {
    get {
      if (_ZoomCooldownTimestampOffset == null) {
        _ZoomCooldownTimestampOffset = Schema.GetOffset(0x43587513F2898D9F);
      }
      return ref _Handle.AsRef<float>(_ZoomCooldownTimestampOffset!.Value);
    }
  }
  private static nint? _DoneAimingOffset;

  public ref bool DoneAiming {
    get {
      if (_DoneAimingOffset == null) {
        _DoneAimingOffset = Schema.GetOffset(0x43587513F2C3ADDE);
      }
      return ref _Handle.AsRef<bool>(_DoneAimingOffset!.Value);
    }
  }
  private static nint? _LerpStartTimeOffset;

  public ref float LerpStartTime {
    get {
      if (_LerpStartTimeOffset == null) {
        _LerpStartTimeOffset = Schema.GetOffset(0x43587513B67B575F);
      }
      return ref _Handle.AsRef<float>(_LerpStartTimeOffset!.Value);
    }
  }
  private static nint? _NextLookTargetLerpTimeOffset;

  public ref float NextLookTargetLerpTime {
    get {
      if (_NextLookTargetLerpTimeOffset == null) {
        _NextLookTargetLerpTimeOffset = Schema.GetOffset(0x43587513768D7F08);
      }
      return ref _Handle.AsRef<float>(_NextLookTargetLerpTimeOffset!.Value);
    }
  }
  private static nint? _PenaltyReductionRatioOffset;

  public ref float PenaltyReductionRatio {
    get {
      if (_PenaltyReductionRatioOffset == null) {
        _PenaltyReductionRatioOffset = Schema.GetOffset(0x43587513BB3B4A10);
      }
      return ref _Handle.AsRef<float>(_PenaltyReductionRatioOffset!.Value);
    }
  }
  private static nint? _NextLookTargetOffset;

  public ref QAngle NextLookTarget {
    get {
      if (_NextLookTargetOffset == null) {
        _NextLookTargetOffset = Schema.GetOffset(0x43587513C1D3F3CE);
      }
      return ref _Handle.AsRef<QAngle>(_NextLookTargetOffset!.Value);
    }
  }
  private static nint? _AimTimerOffset;

  public CountdownTimer AimTimer {
    get {
      if (_AimTimerOffset == null) {
        _AimTimerOffset = Schema.GetOffset(0x4358751330E31F47);
      }
      return new CountdownTimerImpl(_Handle + _AimTimerOffset!.Value);
    }
  }
  private static nint? _SniperHoldTimerOffset;

  public CountdownTimer SniperHoldTimer {
    get {
      if (_SniperHoldTimerOffset == null) {
        _SniperHoldTimerOffset = Schema.GetOffset(0x43587513B206F2AC);
      }
      return new CountdownTimerImpl(_Handle + _SniperHoldTimerOffset!.Value);
    }
  }
  private static nint? _FocusIntervalTimerOffset;

  public CountdownTimer FocusIntervalTimer {
    get {
      if (_FocusIntervalTimerOffset == null) {
        _FocusIntervalTimerOffset = Schema.GetOffset(0x43587513267063CB);
      }
      return new CountdownTimerImpl(_Handle + _FocusIntervalTimerOffset!.Value);
    }
  }
  private static nint? _AcquiredOffset;

  public ref bool Acquired {
    get {
      if (_AcquiredOffset == null) {
        _AcquiredOffset = Schema.GetOffset(0x435875131D2FE5B5);
      }
      return ref _Handle.AsRef<bool>(_AcquiredOffset!.Value);
    }
  }


}