// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CDestructiblePart_DamageLevelImpl : SchemaClass, CDestructiblePart_DamageLevel {

  public CDestructiblePart_DamageLevelImpl(nint handle) : base(handle) {
  }

  private static nint? _NameOffset;

  public string Name {
    get {
      if (_NameOffset == null) {
        _NameOffset = Schema.GetOffset(0xF69D69CB63D22D49);
      }
      var ptr = _Handle.Read<nint>(_NameOffset!.Value);
      return Schema.GetString(ptr);
    }
    set {
      if (_NameOffset == null) {
        _NameOffset = Schema.GetOffset(0xF69D69CB63D22D49);
      }
      Schema.SetString(_Handle, _NameOffset!.Value, value);
    }
  } 
  private static nint? _BreakablePieceNameOffset;

  public ref CGlobalSymbol BreakablePieceName {
    get {
      if (_BreakablePieceNameOffset == null) {
        _BreakablePieceNameOffset = Schema.GetOffset(0xF69D69CB88329BEA);
      }
      return ref _Handle.AsRef<CGlobalSymbol>(_BreakablePieceNameOffset!.Value);
    }
  }
  private static nint? _BodyGroupValueOffset;

  public ref int BodyGroupValue {
    get {
      if (_BodyGroupValueOffset == null) {
        _BodyGroupValueOffset = Schema.GetOffset(0xF69D69CB90FF4BE9);
      }
      return ref _Handle.AsRef<int>(_BodyGroupValueOffset!.Value);
    }
  }
  private static nint? _HealthOffset;

  public CSkillInt Health {
    get {
      if (_HealthOffset == null) {
        _HealthOffset = Schema.GetOffset(0xF69D69CB6E9C4CC3);
      }
      return new CSkillIntImpl(_Handle + _HealthOffset!.Value);
    }
  }
  private static nint? _CriticalDamagePercentOffset;

  public ref float CriticalDamagePercent {
    get {
      if (_CriticalDamagePercentOffset == null) {
        _CriticalDamagePercentOffset = Schema.GetOffset(0xF69D69CB4488F688);
      }
      return ref _Handle.AsRef<float>(_CriticalDamagePercentOffset!.Value);
    }
  }
  private static nint? _DamagePassthroughTypeOffset;

  public ref EDestructiblePartDamagePassThroughType DamagePassthroughType {
    get {
      if (_DamagePassthroughTypeOffset == null) {
        _DamagePassthroughTypeOffset = Schema.GetOffset(0xF69D69CB3D01100A);
      }
      return ref _Handle.AsRef<EDestructiblePartDamagePassThroughType>(_DamagePassthroughTypeOffset!.Value);
    }
  }
  private static nint? _DestructionDeathBehaviorOffset;

  public ref DestructiblePartDestructionDeathBehavior_t DestructionDeathBehavior {
    get {
      if (_DestructionDeathBehaviorOffset == null) {
        _DestructionDeathBehaviorOffset = Schema.GetOffset(0xF69D69CB41778385);
      }
      return ref _Handle.AsRef<DestructiblePartDestructionDeathBehavior_t>(_DestructionDeathBehaviorOffset!.Value);
    }
  }
  private static nint? _CustomDeathHandshakeOffset;

  public ref CGlobalSymbol CustomDeathHandshake {
    get {
      if (_CustomDeathHandshakeOffset == null) {
        _CustomDeathHandshakeOffset = Schema.GetOffset(0xF69D69CBF17A0D42);
      }
      return ref _Handle.AsRef<CGlobalSymbol>(_CustomDeathHandshakeOffset!.Value);
    }
  }
  private static nint? _ShouldDestroyOnDeathOffset;

  public ref bool ShouldDestroyOnDeath {
    get {
      if (_ShouldDestroyOnDeathOffset == null) {
        _ShouldDestroyOnDeathOffset = Schema.GetOffset(0xF69D69CBC63DDDD5);
      }
      return ref _Handle.AsRef<bool>(_ShouldDestroyOnDeathOffset!.Value);
    }
  }
  private static nint? _DeathDestroyTimeOffset;

  public CRangeFloat DeathDestroyTime {
    get {
      if (_DeathDestroyTimeOffset == null) {
        _DeathDestroyTimeOffset = Schema.GetOffset(0xF69D69CB29D83EA2);
      }
      return new CRangeFloatImpl(_Handle + _DeathDestroyTimeOffset!.Value);
    }
  }


}