// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CEnvTiltImpl : CPointEntityImpl, CEnvTilt {

  public CEnvTiltImpl(nint handle) : base(handle) {
  }

  private static nint? _DurationOffset;

  public ref float Duration {
    get {
      if (_DurationOffset == null) {
        _DurationOffset = Schema.GetOffset(0xF90425169879A98D);
      }
      return ref _Handle.AsRef<float>(_DurationOffset!.Value);
    }
  }
  private static nint? _RadiusOffset;

  public ref float Radius {
    get {
      if (_RadiusOffset == null) {
        _RadiusOffset = Schema.GetOffset(0xF90425167C5B0533);
      }
      return ref _Handle.AsRef<float>(_RadiusOffset!.Value);
    }
  }
  private static nint? _TiltTimeOffset;

  public ref float TiltTime {
    get {
      if (_TiltTimeOffset == null) {
        _TiltTimeOffset = Schema.GetOffset(0xF9042516B3956BFF);
      }
      return ref _Handle.AsRef<float>(_TiltTimeOffset!.Value);
    }
  }
  private static nint? _StopTimeOffset;

  public GameTime_t StopTime {
    get {
      if (_StopTimeOffset == null) {
        _StopTimeOffset = Schema.GetOffset(0xF90425166BFFEDC4);
      }
      return new GameTime_tImpl(_Handle + _StopTimeOffset!.Value);
    }
  }


}