// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CLogicDistanceAutosaveImpl : CLogicalEntityImpl, CLogicDistanceAutosave {

  public CLogicDistanceAutosaveImpl(nint handle) : base(handle) {
  }

  private static nint? _TargetEntityOffset;

  public string TargetEntity {
    get {
      if (_TargetEntityOffset == null) {
        _TargetEntityOffset = Schema.GetOffset(0x8E908EDD8951B0FB);
      }
      var ptr = _Handle.Read<nint>(_TargetEntityOffset!.Value);
      return Schema.GetString(ptr);
    }
    set {
      if (_TargetEntityOffset == null) {
        _TargetEntityOffset = Schema.GetOffset(0x8E908EDD8951B0FB);
      }
      Schema.SetString(_Handle, _TargetEntityOffset!.Value, value);
    }
  } 
  private static nint? _DistanceToPlayerOffset;

  public ref float DistanceToPlayer {
    get {
      if (_DistanceToPlayerOffset == null) {
        _DistanceToPlayerOffset = Schema.GetOffset(0x8E908EDDF04AFE0C);
      }
      return ref _Handle.AsRef<float>(_DistanceToPlayerOffset!.Value);
    }
  }
  private static nint? _ForceNewLevelUnitOffset;

  public ref bool ForceNewLevelUnit {
    get {
      if (_ForceNewLevelUnitOffset == null) {
        _ForceNewLevelUnitOffset = Schema.GetOffset(0x8E908EDD1473BFDE);
      }
      return ref _Handle.AsRef<bool>(_ForceNewLevelUnitOffset!.Value);
    }
  }
  private static nint? _CheckCoughOffset;

  public ref bool CheckCough {
    get {
      if (_CheckCoughOffset == null) {
        _CheckCoughOffset = Schema.GetOffset(0x8E908EDD25C565C3);
      }
      return ref _Handle.AsRef<bool>(_CheckCoughOffset!.Value);
    }
  }
  private static nint? _ThinkDangerousOffset;

  public ref bool ThinkDangerous {
    get {
      if (_ThinkDangerousOffset == null) {
        _ThinkDangerousOffset = Schema.GetOffset(0x8E908EDDE079F1C9);
      }
      return ref _Handle.AsRef<bool>(_ThinkDangerousOffset!.Value);
    }
  }
  private static nint? _DangerousTimeOffset;

  public ref float DangerousTime {
    get {
      if (_DangerousTimeOffset == null) {
        _DangerousTimeOffset = Schema.GetOffset(0x8E908EDD19BC5644);
      }
      return ref _Handle.AsRef<float>(_DangerousTimeOffset!.Value);
    }
  }


}