// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMapInfoImpl : CPointEntityImpl, CMapInfo {

  public CMapInfoImpl(nint handle) : base(handle) {
  }

  private static nint? _BuyingStatusOffset;

  public ref int BuyingStatus {
    get {
      if (_BuyingStatusOffset == null) {
        _BuyingStatusOffset = Schema.GetOffset(0x64779D004D95482E);
      }
      return ref _Handle.AsRef<int>(_BuyingStatusOffset!.Value);
    }
  }
  private static nint? _BombRadiusOffset;

  public ref float BombRadius {
    get {
      if (_BombRadiusOffset == null) {
        _BombRadiusOffset = Schema.GetOffset(0x64779D009E7FF135);
      }
      return ref _Handle.AsRef<float>(_BombRadiusOffset!.Value);
    }
  }
  private static nint? _PetPopulationOffset;

  public ref int PetPopulation {
    get {
      if (_PetPopulationOffset == null) {
        _PetPopulationOffset = Schema.GetOffset(0x64779D00BCEEB4DA);
      }
      return ref _Handle.AsRef<int>(_PetPopulationOffset!.Value);
    }
  }
  private static nint? _UseNormalSpawnsForDMOffset;

  public ref bool UseNormalSpawnsForDM {
    get {
      if (_UseNormalSpawnsForDMOffset == null) {
        _UseNormalSpawnsForDMOffset = Schema.GetOffset(0x64779D007D2B7341);
      }
      return ref _Handle.AsRef<bool>(_UseNormalSpawnsForDMOffset!.Value);
    }
  }
  private static nint? _DisableAutoGeneratedDMSpawnsOffset;

  public ref bool DisableAutoGeneratedDMSpawns {
    get {
      if (_DisableAutoGeneratedDMSpawnsOffset == null) {
        _DisableAutoGeneratedDMSpawnsOffset = Schema.GetOffset(0x64779D001002982A);
      }
      return ref _Handle.AsRef<bool>(_DisableAutoGeneratedDMSpawnsOffset!.Value);
    }
  }
  private static nint? _BotMaxVisionDistanceOffset;

  public ref float BotMaxVisionDistance {
    get {
      if (_BotMaxVisionDistanceOffset == null) {
        _BotMaxVisionDistanceOffset = Schema.GetOffset(0x64779D00C24A99A9);
      }
      return ref _Handle.AsRef<float>(_BotMaxVisionDistanceOffset!.Value);
    }
  }
  private static nint? _HostageCountOffset;

  public ref int HostageCount {
    get {
      if (_HostageCountOffset == null) {
        _HostageCountOffset = Schema.GetOffset(0x64779D00712B11F0);
      }
      return ref _Handle.AsRef<int>(_HostageCountOffset!.Value);
    }
  }
  private static nint? _FadePlayerVisibilityFarZOffset;

  public ref bool FadePlayerVisibilityFarZ {
    get {
      if (_FadePlayerVisibilityFarZOffset == null) {
        _FadePlayerVisibilityFarZOffset = Schema.GetOffset(0x64779D00747F0977);
      }
      return ref _Handle.AsRef<bool>(_FadePlayerVisibilityFarZOffset!.Value);
    }
  }
  private static nint? _RainTraceToSkyEnabledOffset;

  public ref bool RainTraceToSkyEnabled {
    get {
      if (_RainTraceToSkyEnabledOffset == null) {
        _RainTraceToSkyEnabledOffset = Schema.GetOffset(0x64779D009EB6B2C7);
      }
      return ref _Handle.AsRef<bool>(_RainTraceToSkyEnabledOffset!.Value);
    }
  }
  private static nint? _EnvRainStrengthOffset;

  public ref float EnvRainStrength {
    get {
      if (_EnvRainStrengthOffset == null) {
        _EnvRainStrengthOffset = Schema.GetOffset(0x64779D006B9B85E1);
      }
      return ref _Handle.AsRef<float>(_EnvRainStrengthOffset!.Value);
    }
  }
  private static nint? _EnvPuddleRippleStrengthOffset;

  public ref float EnvPuddleRippleStrength {
    get {
      if (_EnvPuddleRippleStrengthOffset == null) {
        _EnvPuddleRippleStrengthOffset = Schema.GetOffset(0x64779D00E94DCDCD);
      }
      return ref _Handle.AsRef<float>(_EnvPuddleRippleStrengthOffset!.Value);
    }
  }
  private static nint? _EnvPuddleRippleDirectionOffset;

  public ref float EnvPuddleRippleDirection {
    get {
      if (_EnvPuddleRippleDirectionOffset == null) {
        _EnvPuddleRippleDirectionOffset = Schema.GetOffset(0x64779D00B1B7BC85);
      }
      return ref _Handle.AsRef<float>(_EnvPuddleRippleDirectionOffset!.Value);
    }
  }
  private static nint? _EnvWetnessCoverageOffset;

  public ref float EnvWetnessCoverage {
    get {
      if (_EnvWetnessCoverageOffset == null) {
        _EnvWetnessCoverageOffset = Schema.GetOffset(0x64779D001005A92B);
      }
      return ref _Handle.AsRef<float>(_EnvWetnessCoverageOffset!.Value);
    }
  }
  private static nint? _EnvWetnessDryingAmountOffset;

  public ref float EnvWetnessDryingAmount {
    get {
      if (_EnvWetnessDryingAmountOffset == null) {
        _EnvWetnessDryingAmountOffset = Schema.GetOffset(0x64779D00FC4DB04E);
      }
      return ref _Handle.AsRef<float>(_EnvWetnessDryingAmountOffset!.Value);
    }
  }


}