// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmFootstepEventIDNode__CDefinitionImpl : CNmIDValueNode__CDefinitionImpl, CNmFootstepEventIDNode__CDefinition {

  public CNmFootstepEventIDNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  private static nint? _SourceStateNodeIdxOffset;

  public ref short SourceStateNodeIdx {
    get {
      if (_SourceStateNodeIdxOffset == null) {
        _SourceStateNodeIdxOffset = Schema.GetOffset(0x2CDDA43263F0228C);
      }
      return ref _Handle.AsRef<short>(_SourceStateNodeIdxOffset!.Value);
    }
  }
  private static nint? _EventConditionRulesOffset;

  public CNmBitFlags EventConditionRules {
    get {
      if (_EventConditionRulesOffset == null) {
        _EventConditionRulesOffset = Schema.GetOffset(0x2CDDA432A904315F);
      }
      return new CNmBitFlagsImpl(_Handle + _EventConditionRulesOffset!.Value);
    }
  }


}