// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmStateMachineNode__TransitionDefinition_tImpl : SchemaClass, CNmStateMachineNode__TransitionDefinition_t {

  public CNmStateMachineNode__TransitionDefinition_tImpl(nint handle) : base(handle) {
  }

  private static nint? _TargetStateIdxOffset;

  public ref short TargetStateIdx {
    get {
      if (_TargetStateIdxOffset == null) {
        _TargetStateIdxOffset = Schema.GetOffset(0x9404D2C4E5C0218C);
      }
      return ref _Handle.AsRef<short>(_TargetStateIdxOffset!.Value);
    }
  }
  private static nint? _ConditionNodeIdxOffset;

  public ref short ConditionNodeIdx {
    get {
      if (_ConditionNodeIdxOffset == null) {
        _ConditionNodeIdxOffset = Schema.GetOffset(0x9404D2C4773FE641);
      }
      return ref _Handle.AsRef<short>(_ConditionNodeIdxOffset!.Value);
    }
  }
  private static nint? _TransitionNodeIdxOffset;

  public ref short TransitionNodeIdx {
    get {
      if (_TransitionNodeIdxOffset == null) {
        _TransitionNodeIdxOffset = Schema.GetOffset(0x9404D2C40D5CDE45);
      }
      return ref _Handle.AsRef<short>(_TransitionNodeIdxOffset!.Value);
    }
  }
  private static nint? _CanBeForcedOffset;

  public ref bool CanBeForced {
    get {
      if (_CanBeForcedOffset == null) {
        _CanBeForcedOffset = Schema.GetOffset(0x9404D2C4B6EB0555);
      }
      return ref _Handle.AsRef<bool>(_CanBeForcedOffset!.Value);
    }
  }


}