// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmTargetInfoNode__CDefinitionImpl : CNmFloatValueNode__CDefinitionImpl, CNmTargetInfoNode__CDefinition {

  public CNmTargetInfoNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  private static nint? _InputValueNodeIdxOffset;

  public ref short InputValueNodeIdx {
    get {
      if (_InputValueNodeIdxOffset == null) {
        _InputValueNodeIdxOffset = Schema.GetOffset(0x2288EABA95E89F27);
      }
      return ref _Handle.AsRef<short>(_InputValueNodeIdxOffset!.Value);
    }
  }
  private static nint? _InfoTypeOffset;

  public ref CNmTargetInfoNode__Info_t InfoType {
    get {
      if (_InfoTypeOffset == null) {
        _InfoTypeOffset = Schema.GetOffset(0x2288EABACE6BA20D);
      }
      return ref _Handle.AsRef<CNmTargetInfoNode__Info_t>(_InfoTypeOffset!.Value);
    }
  }
  private static nint? _IsWorldSpaceTargetOffset;

  public ref bool IsWorldSpaceTarget {
    get {
      if (_IsWorldSpaceTargetOffset == null) {
        _IsWorldSpaceTargetOffset = Schema.GetOffset(0x2288EABAB81D53F2);
      }
      return ref _Handle.AsRef<bool>(_IsWorldSpaceTargetOffset!.Value);
    }
  }


}