// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPointClientUIWorldTextPanelImpl : CPointClientUIWorldPanelImpl, CPointClientUIWorldTextPanel {

  public CPointClientUIWorldTextPanelImpl(nint handle) : base(handle) {
  }

  private static nint? _MessageTextOffset;

  public string MessageText {
    get {
        if (_MessageTextOffset == null) {
            _MessageTextOffset = Schema.GetOffset(0x9F10465EBA6E5D73);
        }
        var ptr = _Handle + _MessageTextOffset!.Value;
        return Schema.GetString(ptr);
    }
    set {
        if (_MessageTextOffset == null) {
            _MessageTextOffset = Schema.GetOffset(0x9F10465EBA6E5D73);
        }
        Schema.SetFixedString(_Handle, _MessageTextOffset!.Value, value, 512);
    }
  } 

  public void MessageTextUpdated() {
    Schema.Update(_Handle, 0x9F10465EBA6E5D73);
  }
}