// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_TimelineImpl : CPulseCell_BaseYieldingInflowImpl, CPulseCell_Timeline {

  public CPulseCell_TimelineImpl(nint handle) : base(handle) {
  }

  private static nint? _TimelineEventsOffset;

  public ref CUtlVector<CPulseCell_Timeline__TimelineEvent_t> TimelineEvents {
    get {
      if (_TimelineEventsOffset == null) {
        _TimelineEventsOffset = Schema.GetOffset(0xF1185F93C91CDDC3);
      }
      return ref _Handle.AsRef<CUtlVector<CPulseCell_Timeline__TimelineEvent_t>>(_TimelineEventsOffset!.Value);
    }
  }
  private static nint? _WaitForChildOutflowsOffset;

  public ref bool WaitForChildOutflows {
    get {
      if (_WaitForChildOutflowsOffset == null) {
        _WaitForChildOutflowsOffset = Schema.GetOffset(0xF1185F933F8E29C6);
      }
      return ref _Handle.AsRef<bool>(_WaitForChildOutflowsOffset!.Value);
    }
  }
  private static nint? _OnFinishedOffset;

  public CPulse_ResumePoint OnFinished {
    get {
      if (_OnFinishedOffset == null) {
        _OnFinishedOffset = Schema.GetOffset(0xF1185F938D903E5E);
      }
      return new CPulse_ResumePointImpl(_Handle + _OnFinishedOffset!.Value);
    }
  }
  private static nint? _OnCanceledOffset;

  public CPulse_ResumePoint OnCanceled {
    get {
      if (_OnCanceledOffset == null) {
        _OnCanceledOffset = Schema.GetOffset(0xF1185F93F02162DB);
      }
      return new CPulse_ResumePointImpl(_Handle + _OnCanceledOffset!.Value);
    }
  }


}