// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSequenceFinishedAnimTagImpl : CAnimTagBaseImpl, CSequenceFinishedAnimTag {

  public CSequenceFinishedAnimTagImpl(nint handle) : base(handle) {
  }

  private static nint? _SequenceNameOffset;

  public string SequenceName {
    get {
      if (_SequenceNameOffset == null) {
        _SequenceNameOffset = Schema.GetOffset(0x1B46C5202B4A24CB);
      }
      var ptr = _Handle.Read<nint>(_SequenceNameOffset!.Value);
      return Schema.GetString(ptr);
    }
    set {
      if (_SequenceNameOffset == null) {
        _SequenceNameOffset = Schema.GetOffset(0x1B46C5202B4A24CB);
      }
      Schema.SetString(_Handle, _SequenceNameOffset!.Value, value);
    }
  } 


}