// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTestEffectImpl : CBaseEntityImpl, CTestEffect {

  public CTestEffectImpl(nint handle) : base(handle) {
  }

  private static nint? _LoopOffset;

  public ref int Loop {
    get {
      if (_LoopOffset == null) {
        _LoopOffset = Schema.GetOffset(0xF4103FBFFFB6D07A);
      }
      return ref _Handle.AsRef<int>(_LoopOffset!.Value);
    }
  }
  private static nint? _BeamOffset;

  public ref int Beam {
    get {
      if (_BeamOffset == null) {
        _BeamOffset = Schema.GetOffset(0xF4103FBF54034EE3);
      }
      return ref _Handle.AsRef<int>(_BeamOffset!.Value);
    }
  }
  private static nint? _Beam1Offset;

  public SchemaUntypedField Beam1 {
    get {
      if (_Beam1Offset == null) {
        _Beam1Offset = Schema.GetOffset(0xF4103FBFC4017428);
      }
      return new SchemaUntypedField(_Handle + _Beam1Offset!.Value);
    }
  }
  private static nint? _BeamTimeOffset;

  public SchemaUntypedField BeamTime {
    get {
      if (_BeamTimeOffset == null) {
        _BeamTimeOffset = Schema.GetOffset(0xF4103FBF60293F01);
      }
      return new SchemaUntypedField(_Handle + _BeamTimeOffset!.Value);
    }
  }
  private static nint? _StartTimeOffset;

  public GameTime_t StartTime {
    get {
      if (_StartTimeOffset == null) {
        _StartTimeOffset = Schema.GetOffset(0xF4103FBF67FE9DC4);
      }
      return new GameTime_tImpl(_Handle + _StartTimeOffset!.Value);
    }
  }


}