// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTimeRemainingMetricEvaluatorImpl : CMotionMetricEvaluatorImpl, CTimeRemainingMetricEvaluator {

  public CTimeRemainingMetricEvaluatorImpl(nint handle) : base(handle) {
  }

  private static nint? _MatchByTimeRemainingOffset;

  public ref bool MatchByTimeRemaining {
    get {
      if (_MatchByTimeRemainingOffset == null) {
        _MatchByTimeRemainingOffset = Schema.GetOffset(0xAB802C86BB70462E);
      }
      return ref _Handle.AsRef<bool>(_MatchByTimeRemainingOffset!.Value);
    }
  }
  private static nint? _MaxTimeRemainingOffset;

  public ref float MaxTimeRemaining {
    get {
      if (_MaxTimeRemainingOffset == null) {
        _MaxTimeRemainingOffset = Schema.GetOffset(0xAB802C8686818AD6);
      }
      return ref _Handle.AsRef<float>(_MaxTimeRemainingOffset!.Value);
    }
  }
  private static nint? _FilterByTimeRemainingOffset;

  public ref bool FilterByTimeRemaining {
    get {
      if (_FilterByTimeRemainingOffset == null) {
        _FilterByTimeRemainingOffset = Schema.GetOffset(0xAB802C8668E9E5BD);
      }
      return ref _Handle.AsRef<bool>(_FilterByTimeRemainingOffset!.Value);
    }
  }
  private static nint? _MinTimeRemainingOffset;

  public ref float MinTimeRemaining {
    get {
      if (_MinTimeRemainingOffset == null) {
        _MinTimeRemainingOffset = Schema.GetOffset(0xAB802C8604DD377C);
      }
      return ref _Handle.AsRef<float>(_MinTimeRemainingOffset!.Value);
    }
  }


}