// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTriggerHurtImpl : CBaseTriggerImpl, CTriggerHurt {

  public CTriggerHurtImpl(nint handle) : base(handle) {
  }

  private static nint? _OriginalDamageOffset;

  public ref float OriginalDamage {
    get {
      if (_OriginalDamageOffset == null) {
        _OriginalDamageOffset = Schema.GetOffset(0x8D02278785B50515);
      }
      return ref _Handle.AsRef<float>(_OriginalDamageOffset!.Value);
    }
  }
  private static nint? _DamageOffset;

  public ref float Damage {
    get {
      if (_DamageOffset == null) {
        _DamageOffset = Schema.GetOffset(0x8D022787DC60E53E);
      }
      return ref _Handle.AsRef<float>(_DamageOffset!.Value);
    }
  }
  private static nint? _DamageCapOffset;

  public ref float DamageCap {
    get {
      if (_DamageCapOffset == null) {
        _DamageCapOffset = Schema.GetOffset(0x8D022787AED58F86);
      }
      return ref _Handle.AsRef<float>(_DamageCapOffset!.Value);
    }
  }
  private static nint? _LastDmgTimeOffset;

  public GameTime_t LastDmgTime {
    get {
      if (_LastDmgTimeOffset == null) {
        _LastDmgTimeOffset = Schema.GetOffset(0x8D022787BF3F1360);
      }
      return new GameTime_tImpl(_Handle + _LastDmgTimeOffset!.Value);
    }
  }
  private static nint? _ForgivenessDelayOffset;

  public ref float ForgivenessDelay {
    get {
      if (_ForgivenessDelayOffset == null) {
        _ForgivenessDelayOffset = Schema.GetOffset(0x8D022787112B0E13);
      }
      return ref _Handle.AsRef<float>(_ForgivenessDelayOffset!.Value);
    }
  }
  private static nint? _BitsDamageInflictOffset;

  public ref DamageTypes_t BitsDamageInflict {
    get {
      if (_BitsDamageInflictOffset == null) {
        _BitsDamageInflictOffset = Schema.GetOffset(0x8D0227876F0ADA0F);
      }
      return ref _Handle.AsRef<DamageTypes_t>(_BitsDamageInflictOffset!.Value);
    }
  }
  private static nint? _DamageModelOffset;

  public ref int DamageModel {
    get {
      if (_DamageModelOffset == null) {
        _DamageModelOffset = Schema.GetOffset(0x8D022787076F74AD);
      }
      return ref _Handle.AsRef<int>(_DamageModelOffset!.Value);
    }
  }
  private static nint? _NoDmgForceOffset;

  public ref bool NoDmgForce {
    get {
      if (_NoDmgForceOffset == null) {
        _NoDmgForceOffset = Schema.GetOffset(0x8D0227878236F03D);
      }
      return ref _Handle.AsRef<bool>(_NoDmgForceOffset!.Value);
    }
  }
  private static nint? _DamageForceOffset;

  public ref Vector DamageForce {
    get {
      if (_DamageForceOffset == null) {
        _DamageForceOffset = Schema.GetOffset(0x8D022787B66401B7);
      }
      return ref _Handle.AsRef<Vector>(_DamageForceOffset!.Value);
    }
  }
  private static nint? _ThinkAlwaysOffset;

  public ref bool ThinkAlways {
    get {
      if (_ThinkAlwaysOffset == null) {
        _ThinkAlwaysOffset = Schema.GetOffset(0x8D02278776BDBDDA);
      }
      return ref _Handle.AsRef<bool>(_ThinkAlwaysOffset!.Value);
    }
  }
  private static nint? _HurtThinkPeriodOffset;

  public ref float HurtThinkPeriod {
    get {
      if (_HurtThinkPeriodOffset == null) {
        _HurtThinkPeriodOffset = Schema.GetOffset(0x8D022787C98165F1);
      }
      return ref _Handle.AsRef<float>(_HurtThinkPeriodOffset!.Value);
    }
  }
  private static nint? _OnHurtOffset;

  public CEntityIOOutput OnHurt {
    get {
      if (_OnHurtOffset == null) {
        _OnHurtOffset = Schema.GetOffset(0x8D022787361573C1);
      }
      return new CEntityIOOutputImpl(_Handle + _OnHurtOffset!.Value);
    }
  }
  private static nint? _OnHurtPlayerOffset;

  public CEntityIOOutput OnHurtPlayer {
    get {
      if (_OnHurtPlayerOffset == null) {
        _OnHurtPlayerOffset = Schema.GetOffset(0x8D02278771C2F34C);
      }
      return new CEntityIOOutputImpl(_Handle + _OnHurtPlayerOffset!.Value);
    }
  }
  private static nint? _HurtEntitiesOffset;

  public ref CUtlVector<CHandle<CBaseEntity>> HurtEntities {
    get {
      if (_HurtEntitiesOffset == null) {
        _HurtEntitiesOffset = Schema.GetOffset(0x8D0227874E045AC3);
      }
      return ref _Handle.AsRef<CUtlVector<CHandle<CBaseEntity>>>(_HurtEntitiesOffset!.Value);
    }
  }


}