// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVoiceContainerStaticAdditiveSynth__CToneImpl : SchemaClass, CVoiceContainerStaticAdditiveSynth__CTone {

  public CVoiceContainerStaticAdditiveSynth__CToneImpl(nint handle) : base(handle) {
  }

  private static nint? _HarmonicsOffset;

  public ref CUtlVector<CVoiceContainerStaticAdditiveSynth__CHarmonic> Harmonics {
    get {
      if (_HarmonicsOffset == null) {
        _HarmonicsOffset = Schema.GetOffset(0x1501082A3A08CDBF);
      }
      return ref _Handle.AsRef<CUtlVector<CVoiceContainerStaticAdditiveSynth__CHarmonic>>(_HarmonicsOffset!.Value);
    }
  }
  private static nint? _CurveOffset;

  public SchemaUntypedField Curve {
    get {
      if (_CurveOffset == null) {
        _CurveOffset = Schema.GetOffset(0x1501082ABFFA0B34);
      }
      return new SchemaUntypedField(_Handle + _CurveOffset!.Value);
    }
  }
  private static nint? _SyncInstancesOffset;

  public ref bool SyncInstances {
    get {
      if (_SyncInstancesOffset == null) {
        _SyncInstancesOffset = Schema.GetOffset(0x1501082A21EE9902);
      }
      return ref _Handle.AsRef<bool>(_SyncInstancesOffset!.Value);
    }
  }


}