// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVoxelVisibilityImpl : SchemaClass, CVoxelVisibility {

  public CVoxelVisibilityImpl(nint handle) : base(handle) {
  }

  private static nint? _BaseClusterCountOffset;

  public ref uint BaseClusterCount {
    get {
      if (_BaseClusterCountOffset == null) {
        _BaseClusterCountOffset = Schema.GetOffset(0xDA27CA12A16788C5);
      }
      return ref _Handle.AsRef<uint>(_BaseClusterCountOffset!.Value);
    }
  }
  private static nint? _PVSBytesPerClusterOffset;

  public ref uint PVSBytesPerCluster {
    get {
      if (_PVSBytesPerClusterOffset == null) {
        _PVSBytesPerClusterOffset = Schema.GetOffset(0xDA27CA122C2340E0);
      }
      return ref _Handle.AsRef<uint>(_PVSBytesPerClusterOffset!.Value);
    }
  }
  private static nint? _MinBoundsOffset;

  public ref Vector MinBounds {
    get {
      if (_MinBoundsOffset == null) {
        _MinBoundsOffset = Schema.GetOffset(0xDA27CA12114799FE);
      }
      return ref _Handle.AsRef<Vector>(_MinBoundsOffset!.Value);
    }
  }
  private static nint? _MaxBoundsOffset;

  public ref Vector MaxBounds {
    get {
      if (_MaxBoundsOffset == null) {
        _MaxBoundsOffset = Schema.GetOffset(0xDA27CA12C0B4CE60);
      }
      return ref _Handle.AsRef<Vector>(_MaxBoundsOffset!.Value);
    }
  }
  private static nint? _GridSizeOffset;

  public ref float GridSize {
    get {
      if (_GridSizeOffset == null) {
        _GridSizeOffset = Schema.GetOffset(0xDA27CA12975208C2);
      }
      return ref _Handle.AsRef<float>(_GridSizeOffset!.Value);
    }
  }
  private static nint? _SkyVisibilityClusterOffset;

  public ref uint SkyVisibilityCluster {
    get {
      if (_SkyVisibilityClusterOffset == null) {
        _SkyVisibilityClusterOffset = Schema.GetOffset(0xDA27CA12B43BF514);
      }
      return ref _Handle.AsRef<uint>(_SkyVisibilityClusterOffset!.Value);
    }
  }
  private static nint? _SunVisibilityClusterOffset;

  public ref uint SunVisibilityCluster {
    get {
      if (_SunVisibilityClusterOffset == null) {
        _SunVisibilityClusterOffset = Schema.GetOffset(0xDA27CA12848C92AD);
      }
      return ref _Handle.AsRef<uint>(_SunVisibilityClusterOffset!.Value);
    }
  }
  private static nint? _NodeBlockOffset;

  public VoxelVisBlockOffset_t NodeBlock {
    get {
      if (_NodeBlockOffset == null) {
        _NodeBlockOffset = Schema.GetOffset(0xDA27CA12A64594EA);
      }
      return new VoxelVisBlockOffset_tImpl(_Handle + _NodeBlockOffset!.Value);
    }
  }
  private static nint? _RegionBlockOffset;

  public VoxelVisBlockOffset_t RegionBlock {
    get {
      if (_RegionBlockOffset == null) {
        _RegionBlockOffset = Schema.GetOffset(0xDA27CA121918C67A);
      }
      return new VoxelVisBlockOffset_tImpl(_Handle + _RegionBlockOffset!.Value);
    }
  }
  private static nint? _EnclosedClusterListBlockOffset;

  public VoxelVisBlockOffset_t EnclosedClusterListBlock {
    get {
      if (_EnclosedClusterListBlockOffset == null) {
        _EnclosedClusterListBlockOffset = Schema.GetOffset(0xDA27CA121F5DD1A9);
      }
      return new VoxelVisBlockOffset_tImpl(_Handle + _EnclosedClusterListBlockOffset!.Value);
    }
  }
  private static nint? _EnclosedClustersBlockOffset;

  public VoxelVisBlockOffset_t EnclosedClustersBlock {
    get {
      if (_EnclosedClustersBlockOffset == null) {
        _EnclosedClustersBlockOffset = Schema.GetOffset(0xDA27CA12F75E07CE);
      }
      return new VoxelVisBlockOffset_tImpl(_Handle + _EnclosedClustersBlockOffset!.Value);
    }
  }
  private static nint? _MasksBlockOffset;

  public VoxelVisBlockOffset_t MasksBlock {
    get {
      if (_MasksBlockOffset == null) {
        _MasksBlockOffset = Schema.GetOffset(0xDA27CA121853F2AB);
      }
      return new VoxelVisBlockOffset_tImpl(_Handle + _MasksBlockOffset!.Value);
    }
  }
  private static nint? _VisBlocksOffset;

  public VoxelVisBlockOffset_t VisBlocks {
    get {
      if (_VisBlocksOffset == null) {
        _VisBlocksOffset = Schema.GetOffset(0xDA27CA128C69D893);
      }
      return new VoxelVisBlockOffset_tImpl(_Handle + _VisBlocksOffset!.Value);
    }
  }


}