// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class GameTime_tImpl : SchemaClass, GameTime_t {

  public GameTime_tImpl(nint handle) : base(handle) {
  }

  private static nint? _ValueOffset;

  public ref float Value {
    get {
      if (_ValueOffset == null) {
        _ValueOffset = Schema.GetOffset(0x1DBEBD4DDCB0894A);
      }
      return ref _Handle.AsRef<float>(_ValueOffset!.Value);
    }
  }


}