// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ParticleNode_tImpl : SchemaClass, ParticleNode_t {

  public ParticleNode_tImpl(nint handle) : base(handle) {
  }

  private static nint? _EntityOffset;

  public ref CHandle<CBaseEntity> Entity {
    get {
      if (_EntityOffset == null) {
        _EntityOffset = Schema.GetOffset(0xBECF421C6EBADCB0);
      }
      return ref _Handle.AsRef<CHandle<CBaseEntity>>(_EntityOffset!.Value);
    }
  }
  private static nint? _IndexOffset;

  public ParticleIndex_t Index {
    get {
      if (_IndexOffset == null) {
        _IndexOffset = Schema.GetOffset(0xBECF421C8F270140);
      }
      return new ParticleIndex_tImpl(_Handle + _IndexOffset!.Value);
    }
  }
  private static nint? _StartTimeOffset;

  public GameTime_t StartTime {
    get {
      if (_StartTimeOffset == null) {
        _StartTimeOffset = Schema.GetOffset(0xBECF421C67FE9DC4);
      }
      return new GameTime_tImpl(_Handle + _StartTimeOffset!.Value);
    }
  }
  private static nint? _GrowthDurationOffset;

  public ref float GrowthDuration {
    get {
      if (_GrowthDurationOffset == null) {
        _GrowthDurationOffset = Schema.GetOffset(0xBECF421CF0D91F70);
      }
      return ref _Handle.AsRef<float>(_GrowthDurationOffset!.Value);
    }
  }
  private static nint? _GrowthOriginOffset;

  public ref Vector GrowthOrigin {
    get {
      if (_GrowthOriginOffset == null) {
        _GrowthOriginOffset = Schema.GetOffset(0xBECF421C4A651090);
      }
      return ref _Handle.AsRef<Vector>(_GrowthOriginOffset!.Value);
    }
  }
  private static nint? _EndcapTimeOffset;

  public ref float EndcapTime {
    get {
      if (_EndcapTimeOffset == null) {
        _EndcapTimeOffset = Schema.GetOffset(0xBECF421CCF1342BD);
      }
      return ref _Handle.AsRef<float>(_EndcapTimeOffset!.Value);
    }
  }
  private static nint? _MarkedForDeleteOffset;

  public ref bool MarkedForDelete {
    get {
      if (_MarkedForDeleteOffset == null) {
        _MarkedForDeleteOffset = Schema.GetOffset(0xBECF421C6C9EC48F);
      }
      return ref _Handle.AsRef<bool>(_MarkedForDeleteOffset!.Value);
    }
  }


}