// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ragdollhierarchyjoint_tImpl : SchemaClass, ragdollhierarchyjoint_t {

  public ragdollhierarchyjoint_tImpl(nint handle) : base(handle) {
  }

  private static nint? _ParentIndexOffset;

  public ref int ParentIndex {
    get {
      if (_ParentIndexOffset == null) {
        _ParentIndexOffset = Schema.GetOffset(0x3D7AD556FE49C863);
      }
      return ref _Handle.AsRef<int>(_ParentIndexOffset!.Value);
    }
  }
  private static nint? _ChildIndexOffset;

  public ref int ChildIndex {
    get {
      if (_ChildIndexOffset == null) {
        _ChildIndexOffset = Schema.GetOffset(0x3D7AD556226EC483);
      }
      return ref _Handle.AsRef<int>(_ChildIndexOffset!.Value);
    }
  }


}