// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class VsInputSignatureElement_tImpl : SchemaClass, VsInputSignatureElement_t {

  public VsInputSignatureElement_tImpl(nint handle) : base(handle) {
  }

  private static nint? _NameOffset;

  public string Name {
    get {
        if (_NameOffset == null) {
            _NameOffset = Schema.GetOffset(0xFD3BBE5B5B47C92C);
        }
        var ptr = _Handle + _NameOffset!.Value;
        return Schema.GetString(ptr);
    }
    set {
        if (_NameOffset == null) {
            _NameOffset = Schema.GetOffset(0xFD3BBE5B5B47C92C);
        }
        Schema.SetFixedString(_Handle, _NameOffset!.Value, value, 64);
    }
  } 
  private static nint? _SemanticOffset;

  public string Semantic {
    get {
        if (_SemanticOffset == null) {
            _SemanticOffset = Schema.GetOffset(0xFD3BBE5B14684E6F);
        }
        var ptr = _Handle + _SemanticOffset!.Value;
        return Schema.GetString(ptr);
    }
    set {
        if (_SemanticOffset == null) {
            _SemanticOffset = Schema.GetOffset(0xFD3BBE5B14684E6F);
        }
        Schema.SetFixedString(_Handle, _SemanticOffset!.Value, value, 64);
    }
  } 
  private static nint? _D3DSemanticNameOffset;

  public string D3DSemanticName {
    get {
        if (_D3DSemanticNameOffset == null) {
            _D3DSemanticNameOffset = Schema.GetOffset(0xFD3BBE5B66524995);
        }
        var ptr = _Handle + _D3DSemanticNameOffset!.Value;
        return Schema.GetString(ptr);
    }
    set {
        if (_D3DSemanticNameOffset == null) {
            _D3DSemanticNameOffset = Schema.GetOffset(0xFD3BBE5B66524995);
        }
        Schema.SetFixedString(_Handle, _D3DSemanticNameOffset!.Value, value, 64);
    }
  } 
  private static nint? _D3DSemanticIndexOffset;

  public ref int D3DSemanticIndex {
    get {
      if (_D3DSemanticIndexOffset == null) {
        _D3DSemanticIndexOffset = Schema.GetOffset(0xFD3BBE5B67F2BA80);
      }
      return ref _Handle.AsRef<int>(_D3DSemanticIndexOffset!.Value);
    }
  }


}